server:
  port: 8080

spring:
  application:
    name: mall-backend
  datasource:
    url: jdbc:mysql://localhost:3306/mall_shop?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: sa
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

sa-token:
  token-name: satoken
  timeout: 2592000
  active-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
